### ISSUE TITLE
Exception around flutter_health with dashboards on desktop

### ISSUE THREAD

**Issue by ixici** [matthiasn/lotti#1035]
Scenario:
selecting all health and creating dashboard - some exception occured:
<img width="603" alt="Screenshot 2022-06-09 at 21 06 24" src="https://user-images.githubusercontent.com/55126809/172917123-c030e1e6-7ba1-4626-b096-f3b707e3fbe8.png">
<img width="621" alt="Screenshot 2022-06-09 at 21 06 44" src="https://user-images.githubusercontent.com/55126809/172917149-ecf308fa-3d53-4049-8dc1-c59102c677e9.png">

**Comment by matthiasn** [comment]
Good catch, thanks. Not a big issue thanks to [`runZonedGuarded`](https://api.flutter.dev/flutter/dart-async/runZonedGuarded.html) that prevents the exception to crash the app, but not necessary to pollute logs with this warning of a caught exception.
