### ISSUE TITLE
Remove flutter_datetime_picker lib

### ISSUE THREAD

**Issue by matthiasn** [matthiasn/lotti#1435]
See #1433 and #1434

**Comment by gantanikhilraj** [comment]
I can work on this, you could please brief me about the issue? also you can assign it to me.

**Comment by matthiasn** [comment]
@gantanikhilraj thanks a lot, just seeing your offer now and the library is already removed at this point, see linked PR. However, if would you be interested in improving the test coverage of the widgets using the new Date/Time/DateTime pickers?
