### ISSUE TITLE
Register a Measured Unit

### ISSUE THREAD

**Issue by joannavarrete** [matthiasn/lotti#1489]
I want to log a Measurable Data Type such as weight. Is it possible? or it isn't implemented yet?

Thanks

**Comment by matthiasn** [comment]
Hi @joannavarrete, yes under `Settings > Measurable Data Types`, which can then be used in dashboards. You can then define dashboards under `Settings > Dashboard Management`. You can then also assign a dashboard in the definition of a habit, which will then show the dashboard when completing a habit.

The data type `weight` is special, since weight can be imported from Apple Health. That should in theory also work on Android, but I have not tested that yet.

**Comment by joannavarrete** [comment]
Hi @matthiasn, thanks for your fast repply. 

I´ve already added some Measurable data types, such as my mood base in a scale from 1 to 5 and the number of reps I can do of a certain exercises. Also my blood presure. 

Now I want to log, or register, values for those data types, as per day basis. And be able to see them in the Dashboard and to plot them against other types or habits. Is that possible.

Also, let me tell you that the concept ot the app is wonderful. I´ve been searching for something like this for years.

Thank you very much.

**Comment by matthiasn** [comment]
Thank you for your kind words. Sure that's possible and I use it all day. Let me put together some documentation for you.

**Comment by matthiasn** [comment]
@joannavarrete here's what I do to complete my exercises exercise habit. First, we can add some some measurable data types in `Settings > Measurable Data Types` for each exercise type, e.g. 

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231887183-aa931750-127d-4f98-a717-e4d306061ea8.png">

Then we can define a dashboard in `Settings > Dashboard Management` that contains those measurable data types:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231888294-dd048534-6e5b-4217-86ed-45a0b7f7d1b8.png">

Now we can go to the dashboard and add data, also for past dates if I want to backfill, by clicking the little plus icon on the top right of each:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231886242-cd659bc5-cea5-435a-a394-15fc7e54af3c.png">

I've been tracking data like this for many months. Then recently, I added showing dashboards within the habit completion dialog. First, let's add a Category in `Settings > Categories` (this will also allow filtering for habits later, and the assigned color lets me more quickly assess what needs attention):

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231886663-94ffce81-047f-4468-b190-7214ebcd4589.png">

Some example:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231888104-8cfe5b24-630d-40db-bac8-73079b547516.png">

Now we can add a habit for a daily exercise routine in `Settings > Habits`:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231888540-651fd8e0-7a55-45ae-abfb-38d375f24946.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231888645-f7a00a92-e2f2-495c-8edf-75b7ac5e3410.png">

Besides name, category & dashboard, you can also set a start date, and from what time to show each day on the habits page:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231888829-e046a08c-6265-41f0-8b64-0a714090a611.png">

Now the habit can be tracked on a daily basis on the habits page:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231890075-6792eaf2-2616-4bce-86ec-ac688a7cec17.png">

Tapping the checkmark icon will open the completion dialog. If a dashboard is defined for the habit, it is shown in that dialog:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231890272-f351be22-e2d5-4b6c-ae30-b2f65118d22c.png">

Then in the habit completion dialog, we can then record the repetitions for each exercise and when all done, complete the habit:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231890537-3330d608-d7c9-4283-82c3-aefd498a27e9.png">

Popular previous recordings are shown at the bottom and can be clicked/tapped without having to enter the same number over again.

**Comment by matthiasn** [comment]
For more on the different completion statuses, please check the articles on [Substack](https://matthiasnehlsen.substack.com/p/5-how-to-monitor-habits).

**Comment by matthiasn** [comment]
Health data types such as blood pressure, weight, sleep can also be directly imported from Apple Health or the Android equivalent. With Apple Health that's tested, I use that every day 🤓. On Android, not sure, haven't tried in a while.

**Comment by matthiasn** [comment]
For mood, there are also two different psychological instruments (questionnaires) that can be used for tracking mood and sleep/restedness/fatigue:

- [PANAS](https://en.wikipedia.org/wiki/Positive_and_Negative_Affect_Schedule)
- [CFQ11](https://pubmed.ncbi.nlm.nih.gov/20630259/)

We can select those in the dashboard settings by tapping `Survey Charts` (this part needs some overhaul, the UI is outdated):

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231892903-4ed3db9f-19a0-4838-a323-f96a8a9b1a3e.png">

The surveys can then be filled in the respective dashboard (again by tapping the plus icon):

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231893622-c68b82de-e8e3-48fb-a930-cdf01ab11418.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231893977-52301f95-aaab-4f93-ab30-82695c67cbe5.png">

Same for PANAS:

<img width="563" alt="image" src="https://user-images.githubusercontent.com/1390808/231895134-8d1a3dc1-c867-4b3e-bf07-67c929808e58.png">

This dashboard can then also be used in habits, e.g. for habits where we can monitor that they are indeed filled out.

Hope this helps!

**Comment by joannavarrete** [comment]
Wow, thank you very much for the detailed explanation.

I'm giving it a try and it seems very powerful.

I was using https://snapcraft.io/good-job at the moment, and in that app you can define habits with different periodicity. In that way you don't have to skip 6 days of the week if your habit is write a Sunday gratitude-journal entry for the whole week. And when the statistics are shown it doesn't say that you're failed 6 days, but that only takes it account that sunday.

In lotti, how are shown those habits that are not daily but once or twice per day? are they shown in red? Does it disguise the output?

**Comment by matthiasn** [comment]
@joannavarrete weekly habits are on the list of things I want to finish implementing. There's already [`HabitSchedule.weekly`](https://github.com/matthiasn/lotti/blob/62f90c5d85b71236dd7a5c458aa2f84e96d0da2b/lib/classes/entity_definitions.dart#L18) but it's not actually used yet.

So far I'm helping myself with defining a daily habit and pressing `skip` in the habit completion for habits that have a rhythm that's different from daily. Could for example also be that I want to go running say 2-3x per week, as in this example from the manual:

![Running, skip when not due](https://raw.githubusercontent.com/matthiasn/lotti-docs/main/images/0.9.325+2019/habit_completion_10k_steps_now.png)

Then I get frequently reminded about going running and can plan accordingly, e.g. plan a run tomorrow, and also fail when the last successful completion is too long ago. 

The approach outlined above isn't ideal but serving me relatively well so far. How would you envision using weekly (or n times per week/month) habits in Lotti that would make tracking these habits as smoothly as possible?

**Comment by matthiasn** [comment]
@joannavarrete closing this issue for now, please open a new issue for weekly/non-daily habits if you find that the workaround I described above doesn't suit your needs. Thanks!
