### ISSUE TITLE
App works on linux executable but cmake cannot build the app

### ISSUE THREAD

**Issue by joannavarrete** [matthiasn/lotti#1490]
![image](https://user-images.githubusercontent.com/663982/231832966-707c71a9-1aa3-462c-a9e7-3a7aa4f25aba.png)

The app works fine in this machine but Cmake is not able to build it from the source code.

It seems a flutter error but flutter doctor is ok.

Any ideas?

**Comment by matthiasn** [comment]
@joannavarrete also see #941, I have not been lucky at all with anything related to Flutter via Snap, neither running nor packing it. It does work fine for me on Linux however when installing Flutter [manually](https://docs.flutter.dev/get-started/install/linux#install-flutter-manually).

**Comment by joannavarrete** [comment]
I´ll install flutter manually then. 

I´m mainly a java programmer, a bit of clojure and scala but I´m very exited with this app and i´d like to give a try with dart and flutter.

I´ll let you know.
