### ISSUE TITLE
App language defaults to German

### ISSUE THREAD

**Issue by ArthurKlausHoff** [matthiasn/lotti#1566]
If system is not set to any language supported by the app it will use German.

Happens on Linux and Windows (platforms i tested).

**Comment by ArthurKlausHoff** [comment]
Opened this issue because it clearly says in the README that "English is the primary language" and the German translation is incomplete.

is defaulting to German on purpose?

**Comment by matthiasn** [comment]
Interesting, that should not be the case, thanks for raising this issue. How did you test this, what language was the system set to use so I can try to reproduce?

**Comment by ArthurKlausHoff** [comment]
On Linux i tested whit multiple languages, changing the LANG environment variable (see the table below). Windows was set to Portuguese.


| System Language | App Language  |
| -------------------------- | ---------------------- |
| English (LANG=en_US.UTF-8)  | English |
| French (LANG=fr_FR.UTF-8)  | French  |
| Portuguese (LANG=pt_BR.UTF-8)   | German  |
| Spanish (LANG=es_ES.UTF-8)  | German  |
| Russian (LANG=ru_RU.UTF-8)  | German  |

**Comment by ArthurKlausHoff** [comment]
I think you just to need to add `preferred-supported-locales: [en_US]` to `l10n.yaml` as it says in [flutter internationalization docs](https://docs.flutter.dev/accessibility-and-localization/internationalization#configuring-the-l10nyaml-file).

**Comment by matthiasn** [comment]
@ArthurKlausHoff thanks for your help, should be fixed in the upcoming release that's currently building in GitHub Actions. I was pretty sure that the default would be the language of the `template-arb-file` which would make a lot more sense to me than the somewhat arbitrary alphabetical order.
