### ISSUE TITLE
Build failures

### ISSUE THREAD

**Issue by pmagnuson** [matthiasn/lotti#1621]
I've been trying to run this via Xcode & iPhone 14 simulator.  ran into these errors.

- failed to emit precompiled header '/Users/phil/Library/Developer/Xcode/DerivedData/Runner-bznpplydnxgdpncfadmenvqoizqo/Build/Intermediates.noindex/PrecompiledHeaders/Runner-Bridging-Header-swift_2DLRYW91YUZ2M-clang_3HKTKG99R074F.pch' for bridging header '/Users/phil/Documents/projects/investigation/lotti/ios/Runner/Runner-Bridging-Header.h'
- /Users/phil/Documents/projects/investigation/lotti/ios/Runner/Runner-Bridging-Header.h:2:9 'whisper.h' file not found

Any help appreciated.

**Comment by matthiasn** [comment]
@pmagnuson sorry about that, I'll add it to the README as well. You need to run `get_whisper_cpp_ios` to download and unpack the whisper.cpp source. For macOS, that command is `get_whisper_cpp`.

**Comment by matthiasn** [comment]
Closing this issue because the step above isn't required any more after integrating WhisperKit in #1700.
