### ISSUE TITLE
No obvious way to confirm the creation of saga/story 

### ISSUE THREAD

**Issue by yubrshen** [matthiasn/lotti#26]
In the sub-panel for saga/story, clicking 
'+'
I see the sub-panel to create a saga/story, but I found no way to confirm the creation. There is not a button or equivalent to confirm the creation.

**Comment by matthiasn** [comment]
An empty saga/story entry is created immediately. Then when you change anything, such as title, text, saga for a story, color, you can save it with either the disk symbol in the entry editor menu or CTRL-S, or CMD-S on a Mac. The latter currently only works when the cursor is inside the text editor or an input field. Does that make sense? Or at which stage do you see the confirmation of the entry creation?

**Comment by matthiasn** [comment]
I'm closing this issue since the original app is no longer actively maintained. @yubrshen thanks for raising the issue, I'm curious about your thoughts on the new version.
